name: MinecraftManhuntMoreRunners
version: 1.0
api-version: 1.14
main: org.syndiate.manhuntMultSpeedrunners.Main
author: syndiate
description: A recreation of Dream's Minecraft Manhunt, except it allows for multiple speedrunners, unlike most other plugins.

commands: 
  runner: 
    description: Adds a runner to the manhunt.
    usage: /runner [add|remove|help]
  hunter: 
    description: Adds a hunter to the manhunt.
    usage: /hunter [add|remove|help]
  manhunt: 
    description: Initiates/stops the manhunt.
    usage: /manhunt [start|stop|help]
  track: 
    description: Tracks a speedrunner.
    usage: /track <runnerUsername>